print_time: false  # a flag saying whether to print the time used in each function
use_subset_robot: true  # a flag saying whether to use a subset (true) or the whole data (false)
seed: 1  # random seed
n_samples: 20  # number of random samples to run in the model
default_starting_robot: 1  # starting robot index

improvement_centroid:
  epsilon: 100  # a small number to stop improving if the improvement is less than this number
  skip_after_penalty_count: 20  # if encounter penalty 20 consecutive times while improving, stop improve
